### PR TITLE
Fix error using ES6 destructuring / rest parameters

### PR DESCRIPTION
**Pull request by nevcos**
This PR fixes issue https://github.com/bluetech/ng-annotate-patched/issues/2

As described on the above issue, *ng-annotate-patched* gives errors when handling destructuring on variables and parameters, because in both scenarios there's no variable/parameter name.

This PR fixes the problem by ignoring variables/parameters without a name.

### CODE REVIEW

**Comment by bluetech** [comment]
Unfortunately I think the fix here needs to be quite a bit more complex.

The code in `scopetools.js` collects scopes for identifiers. I haven't dug too deeply on how this is used in the code but I'm working under the assumption that it's important, i.e. needs to be accurate.

ES6 made this corner of the syntax much more complex. For example an assignment like the following is possible:

```js
var {title: englishTitle, translations: [{title: localeTitle}], tag} = {
    title: 'Scratchpad',
    translations: [
       {
        locale: 'de',
        localization_tags: [],
        last_edit: '2014-04-14T08:43:37',
        url: '/de/docs/Tools/Scratchpad',
        title: 'JavaScript-Umgebung'
       }
    ],
    url: '/en-US/docs/Tools/Scratchpad',
    tag: 'scratch'
};
```

It results in the following AST: https://gist.github.com/bluetech/73446277130fb543bc99964c19f38155

The above should add 3 new bindings, `engilishTitle`, `localeTitle` and `tag`, but the fix suggest in the PR will just skip it. I fear this will give a false sense of security and thus I prefer to error out over ignoring. I pushed a commit now which emits slightly more reasonable errors: https://github.com/bluetech/ng-annotate-patched/commit/424a3f545cd63c821bd2fae03d52c89f93b62109

If you are courageous enough to try to make it work properly, that would be great :) You can also try to make it work just enough to fit your needs but still error out on more complex cases.

**Comment by nevcos** [comment]
@bluetech I'm still exploring the code (while I'm trying to fix #4), but I'm convinced that those destructuring scenarios are irrelevant for the lib propose (at least for 99,99% of the scenarios).

Additionally I think that failing the build process just because the lib is not capable of understanding destructuring is unacceptable (like shown on example at #2, it fails even if there's no `ngInject` anywhere, which doesn't make much sense).
I do think it's preferable to silently ignore those (like it's happening now for ES6 classes) so that devs will still be able to use destructuring in the code, and that's exactly what this PR is proposing.

If in meanwhile someone finds a scenario where the lib really needs to handle destructuring, in that case a new issue can be created.

What did you think?

Thanks!

**Comment by bluetech** [comment]
I think the main thing this code is meant to support is the "reference following" described here: https://github.com/bluetech/ng-annotate-patched/blob/fork/IMPLICIT.md#reference-following

It does seem unlikely that destructuring will be involved in such a scenario. So I guess if adding proper support is too difficult, I'm OK with skipping these cases (with a comment saying so).

**Comment by nevcos** [comment]
Yes, unfortunately I believe destructuring it's like opening a pandora box, it could be really complex (like you shown on your example), and that would mean huge changes on the code (without a requirement behind it's impossible for me).

So, in that case I believe we've a deal 👍!
I'll add comments saying that, and it could also be added to the README.

Thanks

**Comment by nevcos** [comment]
@bluetech Merged the code with the new fork changes.
Removed the asserts to prevent the build to fail and added the comments.
Please confirm if everything is OK.

Thanks

**Comment by bluetech** [comment]
Just one comment, can you make the `node.params` case similar to the `node.declarations` case, that is match on `pattern.type` instead of checking if `param.name` exists?

**Comment by nevcos** [comment]
@bluetech Nice suggestion! Fixed it.

Also:
- added tests (with array and object notation in all tests) 
- added rest parameter to the tests because it's also fixed now (on both scenarios the `name` is not defined and the type is not `Identifier`).

The tests are not passing (the same on original fork branch), but there are no new differences/errors.

Thanks

**Comment by bluetech** [comment]
Thanks for the fixes!

> The tests are not passing (the same on original fork branch), but there are no new differences/errors.

For me, in the fork branch, the tests are passing, not sure why they fail for you. Can you show the test failure? In this branch though the tests are failing for too, but not in the tests you added. Here is the failure:

```
ran@ran:~/src/ng-annotate-patched$ npm test

> ng-annotate-patched@1.6.0 test /home/ran/src/ng-annotate-patched
> node tests/run-tests

testing adding annotations
Index: with_annotations.js
===================================================================
--- with_annotations.js
+++ with_annotations.js
@@ -1078,12 +1078,11 @@
 /* @ngInject */
 export var exportVariableFunctionVar2 = function($scope) {}
 exportVariableFunctionVar2.$inject = ["$scope"];
 
-export var exportVariableFunctionVar3 = function($scope) {
+export var exportVariableFunctionVar3 = ["$scope", function($scope) {
     "ngInject";
-}
-exportVariableFunctionVar3.$inject = ["$scope"];
+}]
 
 // issue #2 (ng-annotate-patched) - Error using ES6 destructuring
 
 (function(){
npm ERR! Test failed.  See above for more details.
```

**Comment by bluetech** [comment]
Also, if you could rebase the commits on the `fork` branch and maybe squash them it will be easier for me. Just in case you don't know how to do this, it should be something like this:

```
git checkout fork && git pull
git checkout patch-1
git rebase -i fork
<resolve conflicts>
git push --force-with-lease
```

Thanks for persisting with my requests :)

**Comment by bluetech** [comment]
I applied this in 3d700ae3e19a697cfdbaf1413659b7fa0e2be288. Thanks!

**Pull request closed without merging**
