### PR TITLE
Es6 class support

### PR DESCRIPTION
**Pull request by FRSgit**
Continuation of @nevcos work on #5:

- fixed ES6 feature (which stopped working after merge with current master),
- fixed an expected result file from test suite case,
- simplified functions which return interimSuspects.

### CODE REVIEW

**Comment by bluetech** [comment]
Thanks, I started looking at this but got distracted with other changes. I will take another look in a few days.

**Comment by FRSgit** [comment]
I see that you have changed some files yesterday, let me do merge of fork branch once again.

**Comment by FRSgit** [comment]
Done!

**Comment by FRSgit** [comment]
Or not, I see that automatic merge removed most of your recent changes. I'll go through them once again manually and try to bring everything on good track

**Comment by bluetech** [comment]
Sorry - I didn't mean to add work for you, I thought I'd handle the merge myself. However, if you do want to help, I'd prefer a rebase over a merge (such that there are no merge commits in this branch). That would make things a little easier for me.

**Comment by FRSgit** [comment]
Well, I already have merge commits on my branch, so probably it will be easier for me to just create new branch, rebase with your `fork` branch and then force push as es6-class-support - if github will not get that I'll create new pull request for that as well. Would that be sufficient?

**Comment by bluetech** [comment]
Sure, that'd be fine.

**Comment by FRSgit** [comment]
Okay, I've just redone whole branch from current `fork` (there were many conflicts in a way).
Also, updated README.md and added support for **ignoring** classes which have no arguments in constructors.

**Comment by bluetech** [comment]
Thanks for finishing this work @FRSgit! I ended up merging manually in 0469712. I'll do a release now.

**Comment by nevcos** [comment]
Thanks @FRSgit for finishing this work! 👍 🎉

**Comment by FRSgit** [comment]
Thanks @nevcos for starting it and @bluetech for great continuation of awesome tool!

**Pull request closed without merging**
